### ISSUE TITLE
Strange error when compiling w/ LineageOS

### ISSUE THREAD

**Issue by ghost** [microg/GsfProxy#12]
```
FAILED: packages/apps/GsfProxy/services-framework-proxy/build/outputs/apk/services-framework-proxy-release-unsigned.apk 
/bin/bash -c "(rm -Rf packages/apps/GsfProxy/services-framework-proxy/build ) && (mkdir -p /home/kitty/Code/Android/Lineage/out/target/common/obj/APPS/GsfProxy_intermediates ) && (ln -s /home/kitty/Code/Android/Lineage/out/target/common/obj/APPS/GsfProxy_intermediates packages/apps/GsfProxy/services-framework-proxy/build ) && (echo \"sdk.dir=/home/kitty/Android/Sdk/\" > packages/apps/GsfProxy/local.properties ) && (cd packages/apps/GsfProxy && git submodule update --recursive --init ) && (cd packages/apps/GsfProxy/services-framework-proxy && JAVA_TOOL_OPTIONS=\" -Dfile.encoding=UTF8\" ../gradlew assembleRelease )"
Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/home/kitty/.gradle/wrapper/dists/gradle-2.14.1-all/4cj8p00t3e5ni9e8iofg8ghvk7/gradle-2.14.1/lib/gradle-base-services-2.14.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

FAILURE: Build failed with an exception.

* Where:
Build file '/home/kitty/Code/Android/Lineage/packages/apps/GsfProxy/services-framework-proxy/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':services-framework-proxy'.
> javax/xml/bind/annotation/XmlSchema

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by matnakal77** [comment]
> ```
> FAILED: packages/apps/GsfProxy/services-framework-proxy/build/outputs/apk/services-framework-proxy-release-unsigned.apk 
> /bin/bash -c "(rm -Rf packages/apps/GsfProxy/services-framework-proxy/build ) && (mkdir -p /home/kitty/Code/Android/Lineage/out/target/common/obj/APPS/GsfProxy_intermediates ) && (ln -s /home/kitty/Code/Android/Lineage/out/target/common/obj/APPS/GsfProxy_intermediates packages/apps/GsfProxy/services-framework-proxy/build ) && (echo \"sdk.dir=/home/kitty/Android/Sdk/\" > packages/apps/GsfProxy/local.properties ) && (cd packages/apps/GsfProxy && git submodule update --recursive --init ) && (cd packages/apps/GsfProxy/services-framework-proxy && JAVA_TOOL_OPTIONS=\" -Dfile.encoding=UTF8\" ../gradlew assembleRelease )"
> Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/home/kitty/.gradle/wrapper/dists/gradle-2.14.1-all/4cj8p00t3e5ni9e8iofg8ghvk7/gradle-2.14.1/lib/gradle-base-services-2.14.1.jar) to method java.lang.ClassLoader.getPackages()
> WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/kitty/Code/Android/Lineage/packages/apps/GsfProxy/services-framework-proxy/build.gradle' line: 17
> 
> * What went wrong:
> A problem occurred evaluating project ':services-framework-proxy'.
> > javax/xml/bind/annotation/XmlSchema
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> ```

**Comment by mar-v-in** [comment]
Android.mk build is no longer supported.
