### ISSUE TITLE
Min sdk mismatch

### ISSUE THREAD

**Issue by ale5000-git** [microg/GsfProxy#4]
[Here](https://github.com/microg/android_packages_apps_GsfProxy/blob/master/build.gradle) is 9.

Instead [here](https://github.com/microg/android_packages_apps_GsfProxy/blob/master/services-framework-proxy/src/main/AndroidManifest.xml) is 10.

**Comment by mar-v-in** [comment]
minSdkVersion is no longer in AndroidManifest.xml
